<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MRTDScope.Core</RootNamespace>
    <AssemblyName>MRTDScope.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MRTDScope.Core.Tests" />
  </ItemGroup>

</Project>
