<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>MRTDScope.Cli</RootNamespace>
    <AssemblyName>mrtdscope</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../MRTDScope.Core/MRTDScope.Core.csproj" />
    <ProjectReference Include="../MRTDScope.Pcsc/MRTDScope.Pcsc.csproj" />
    <ProjectReference Include="../MRTDScope.Synthetic/MRTDScope.Synthetic.csproj" />
  </ItemGroup>

</Project>
